name: Jail
main: io.github.devcomi.jail.Main
version: 1.0
api-version: 1.19

commands:
  jail:
    description: "감옥 명령어입니다."
    usage: /<command> [create|help|list|release|remain|remove|send]

permissions:
  jail.immune:
    default: false
    description: "감옥에 면역을 추가해줍니다."
  jail.commands.use:
    default: true
    description: "명령어를 쓸 수 있습니다."
  jail.commands.create:
    default: op
    description: "create 명령어를 쓸 수 있게 해줍니다."
  jail.commands.help:
    default: true
    description: "help 명령어를 쓸 수 있게 해줍니다."
  jail.commands.list:
    default: op
    description: "list 명령어를 쓸 수 있게 해줍니다."
  jail.commands.release:
    default: op
    description: "release 명령어를 쓸 수 있게 해줍니다."
  jail.commands.remain:
    default: true
    description: "remain 명령어를 쓸 수 있게 해줍니다."
  jail.commands.remove:
    default: op
    description: "remove 명령어를 쓸 수 있게 해줍니다."
  jail.commands.send:
    default: op
    description: "send 명령어를 쓸 수 있게 해줍니다."
  jail.commands.*:
    default: op
    description: "모든 명령어를 쓸 수 있게 해줍니다."
    children:
      jail.commands.use: true
      jail.commands.create: true
      jail.commands.help: true
      jail.commands.list: true
      jail.commands.release: true
      jail.commands.remain: true
      jail.commands.remove: true
      jail.commands.send: true